---
# tasks file for deploy_apache_web
- block: #========= Install for "Debian"=========

   - name: Install Apache WebServer
     apt:
       name: apache2
       state: present
       update_cache: yes

   - name: Start Apache and Enable it on the every boot
     service: name=apache2 state=started enabled=yes

  when: ansible_os_family == "Debian"

- block: #========= Install for "RedHat"=========

   - name: Install Apache WebServer
     yum:
       name: httpd
       state: present
       update_cache: yes

   - name: Start Apache and Enable it on the every boot
     service: name=httpd state=started enabled=yes

  when: ansible_os_family == "RedHat"

          #========================================

- name: Generate INDEX.HTML file
  template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555
  notify:
    - Restart Apache RedHat
    - Restart Apache Debian

- name: Copy My HomePage files to servers
  copy:
    src: "{{ item }}"
    dest: "{{ destin_folder }}"
    mode: 0555
  loop:             #копируем через цикл loop, перечисляя все файлы в папке откуда копировать
    - "1.jpg"
  notify:
    - Restart Apache RedHat
    - Restart Apache Debian
